// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrosXBBcuVIuVa8KfpUGggXTt4meSckFM',
    appId: '1:934913489525:web:b3aa930206a4155b5a563c',
    messagingSenderId: '934913489525',
    projectId: 'parents-in-love',
    authDomain: 'parents-in-love.firebaseapp.com',
    storageBucket: 'parents-in-love.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM59iJHFC4J5TDn6ipHNS0OmK8ycP9h90',
    appId: '1:934913489525:android:84653c65c284e1e05a563c',
    messagingSenderId: '934913489525',
    projectId: 'parents-in-love',
    storageBucket: 'parents-in-love.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJNR3oCKuffB5yotrn0ZpKJg1QbldLQw',
    appId: '1:934913489525:ios:13e48f70a8aa53e55a563c',
    messagingSenderId: '934913489525',
    projectId: 'parents-in-love',
    storageBucket: 'parents-in-love.firebasestorage.app',
    iosBundleId: 'com.example.parentsInLove',
  );

}